title: Raneem Almanon
description: Information Security Portfolio
author: "me"
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
repository: "raneemalmanon/raneemalmanon.github.io"
